//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEventService")]
    public interface IEventService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/SaveEvent", ReplyAction="http://tempuri.org/IEventService/SaveEventResponse")]
        string SaveEvent(string eventName, string details, string date, string recurring, string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventService/SaveEvent", ReplyAction="http://tempuri.org/IEventService/SaveEventResponse")]
        System.Threading.Tasks.Task<string> SaveEventAsync(string eventName, string details, string date, string recurring, string file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventServiceChannel : ExpenseTracker.ServiceReference1.IEventService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventServiceClient : System.ServiceModel.ClientBase<ExpenseTracker.ServiceReference1.IEventService>, ExpenseTracker.ServiceReference1.IEventService {
        
        public EventServiceClient() {
        }
        
        public EventServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveEvent(string eventName, string details, string date, string recurring, string file) {
            return base.Channel.SaveEvent(eventName, details, date, recurring, file);
        }
        
        public System.Threading.Tasks.Task<string> SaveEventAsync(string eventName, string details, string date, string recurring, string file) {
            return base.Channel.SaveEventAsync(eventName, details, date, recurring, file);
        }
    }
}
