//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(ExpenseTracker.ExpenseTrackerDBEntities),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets1d6c2953dfd9f287467ad9fcb57c9b00cba0446d1bb813fa317151b65c66a571))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySets1d6c2953dfd9f287467ad9fcb57c9b00cba0446d1bb813fa317151b65c66a571 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "1d6c2953dfd9f287467ad9fcb57c9b00cba0446d1bb813fa317151b65c66a571"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "ExpenseTrackerDBModelStoreContainer.Users")
            {
                return GetView0();
            }

            if (extentName == "ExpenseTrackerDBEntities.Users")
            {
                return GetView1();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for ExpenseTrackerDBModelStoreContainer.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [ExpenseTrackerDBModel.Store.Users](T1.Users_Id, T1.Users_username, T1.Users_password)
    FROM (
        SELECT 
            T.Id AS Users_Id, 
            T.username AS Users_username, 
            T.password AS Users_password, 
            True AS _from0
        FROM ExpenseTrackerDBEntities.Users AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ExpenseTrackerDBEntities.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [ExpenseTrackerDBModel.Users](T1.Users_Id, T1.Users_username, T1.Users_password)
    FROM (
        SELECT 
            T.Id AS Users_Id, 
            T.username AS Users_username, 
            T.password AS Users_password, 
            True AS _from0
        FROM ExpenseTrackerDBModelStoreContainer.Users AS T
    ) AS T1");
        }
    }
}
